### ISSUE TITLE
mac64-natives.tar.xz not found

### ISSUE THREAD

**Issue by SebasRiosR** [dzikoysk/Pandomium#19]
Hi, I am trying to use Pandomium on Mac, but when executing the project it throws an error when downloading the file mac64-natives.tar.xz because it can not find it. I followed the steps to compile on Mac and I already have that file, however, I do not know how to do so that I do not look for that file on the page but use the local file that I generated.

**Comment by dzikoysk** [comment]
Oh, awesome, could you send me your `mac64-natives.tar.xz`? I don't have macOS and I'm not able to build these natives. 

Anyway, you should unpack content of the archive to the directory called `native`, located in your working directory. I'm not sure if it's all, because, as I said, I wasn't able to test macOS support.

**Comment by SebasRiosR** [comment]
Of course, You can download it from this [link](https://drive.google.com/file/d/1y3Krj--Dnoa-RkO5-4Mbz023BC11CnCf/view?usp=sharing). Could you upload it to the [page](https://pandomium.panda-lang.org/download/natives/67.0/) where the others are located?

However, I unzip it with the following command and nothing happens.
`tar -cf - . | xz -9e -c - > macosx64-natives.tar.xz`

Thank's

**Comment by dzikoysk** [comment]
Ok, I see, something went wrong with building. This archive should have ~50mb, natives directory is empty. 

Did you try to launch the test? (https://github.com/dzikoysk/Pandomium/wiki/macOS-Build)
```
# Test
chmod +x native/Release/jcef_app.app
cd native/Release && open jcef_app.app && cd -
```
