### ISSUE TITLE
Logger can't be disabled?

### ISSUE THREAD

**Issue by Osiris-Team** [dzikoysk/pandomium#70]
This isnt working somehow?:
```java
Logger.getLogger("org.panda_lang.pandomium.Pandomium").setLevel(Level.OFF);
```

**Comment by dzikoysk** [comment]
In Pandomium 67.0.7 logger can be configured through settings. You can use default logger that now prints to the standard `System.out`, you can configure custom SLF4J instance or you can just implement logger on your own. More details about the new logging library you may find here:

* https://github.com/reposilite-playground/dynamic-logger

**Comment by Osiris-Team** [comment]
@dzikoysk Could you provide a code example on how to do that?

**Comment by dzikoysk** [comment]
There are various implementations, using an abstract logger it looks like this:

```java
PandomiumSettings settings = PandomiumSettings.getDefaultSettingsBuilder()
        .logger(new DefaultLogger(Channel.ALL) {
            @Override
            protected void internalLog(Channel channel, String message) {
                System.out.println(channel + " | " + message);
            }
        })
        .build();

Pandomium pandomium = new Pandomium(settings);
```

Instead of custom logger, you can use various default implementations:

* https://github.com/reposilite-playground/dynamic-logger/tree/main/dynamic-logger/src/main/java/net/dzikoysk/dynamiclogger/backend
* Slf4J (requires extra dependency) https://github.com/reposilite-playground/dynamic-logger/blob/main/dynamic-logger-slf4j/src/main/java/net/dzikoysk/dynamiclogger/slf4j/Slf4jLogger.java

**Comment by Osiris-Team** [comment]
Thanks!
